# Generated by Django 3.0.8 on 2020-07-27 13:23

import converter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.CharField(max_length=100, validators=[converter.models.clean_s1])),
            ],
        ),
        migrations.CreateModel(
            name='dec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.IntegerField()),
            ],
        ),
    ]
