# Generated by Django 3.0.8 on 2020-07-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_balance_deposit_withdraw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
    ]
