# Generated by Django 3.0.8 on 2020-07-28 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_deposit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
