# Generated by Django 3.0.8 on 2020-07-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_userprofileinfo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='user',
        ),
        migrations.DeleteModel(
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='user',
        ),
        migrations.DeleteModel(
            name='balance',
        ),
        migrations.DeleteModel(
            name='withdraw',
        ),
    ]
