# Generated by Django 3.0.8 on 2020-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.DecimalField(decimal_places=10, max_digits=20)),
                ('n2', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
